### ISSUE TITLE
Refreshing dependencies throw-> ERROR Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by mmauri** [vshaxe/vshaxe#141]
Hi,
Just testing vshaxe extension with an openfl project
After clicking on refresh in the dependencies panel an error is thrown in vscode:
ERROR Cannot read property 'split' of undefined.

Hope the following info helps:
vshaxe 1.8.0
vscode 1.13.1
haxe 3.4.2
openfl 5.1.5
lime 5.2.1

->settings.json
{
    "haxe.displayConfigurations": [
        ["bin/html5/debug/haxe/debug.hxml"]
    ]
}
->tasks.json
{
    "version": "2.0.0",
    "command": "haxe",
    "args": ["bin/html5/debug/haxe/debug.hxml"],
    "problemMatcher": "$haxe"
}

**Comment by Gama11** [comment]
Is there a line number for that error?

**Comment by mmauri** [comment]
Nope.
https://pasteboard.co/gMGwcGkw.png

But maybe the problem, is that I didn't build the project before.
Now, I have typed Ctrl-Shift-B, and after 5 minutes vscode is still initializing completion:
https://pasteboard.co/gN6wfgzr.png

Maybe its only my computer.

BTW vshaxe looks very promising!!

**Comment by Gama11** [comment]
Try `Help -> Toggle Developer Tools` - there's probably a stacktrace there.

The initializing completion thing is usually a cosmetical issue only, but it might mean that your display configuration is invalid (does the hxml file exist?).

**Comment by mmauri** [comment]
Got it! 
The hxml file exists
There are 2 errors in the chrome console:

messageService.ts:125 Cannot read property 'split' of undefined: TypeError: Cannot read property 'split' of undefined
    at Function.StringTools.replace (C:\Users\MarcMauri\.vscode\extensions\nadako.vshaxe-1.8.0\bin\client.js:164:10)
    at vshaxe_dependencyExplorer_DependencyResolver.getDependencyInfo (C:\Users\MarcMauri\.vscode\extensions\nadako.vshaxe-1.8.0\bin\client.js:1398:46)
    at Array.map (native)
    at Function.vshaxe_dependencyExplorer_DependencyResolver.resolveDependencies (C:\Users\MarcMauri\.vscode\extensions\nadako.vshaxe-1.8.0\bin\client.js:1343:20)
    at vshaxe_dependencyExplorer_DependencyExplorer.refreshDependencies (C:\Users\MarcMauri\.vscode\extensions\nadako.vshaxe-1.8.0\bin\client.js:1178:72)
    at C:\Users\MarcMauri\.vscode\extensions\nadako.vshaxe-1.8.0\bin\client.js:1242:37
    at vshaxe_dependencyExplorer_DependencyExplorer.getChildren (C:\Users\MarcMauri\.vscode\extensions\nadako.vshaxe-1.8.0\bin\client.js:1240:10)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:393420
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:57373
    at new n.Class.derive._oncancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:46346)
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
(anonymous) @ mainThreadTreeViews.ts:60
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
e.resolveErr @ ipcRemoteCom.ts:111
f @ ipcRemoteCom.ts:203
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
shell.ts:445 n.slice is not a function: TypeError: n.slice is not a function
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:192417
    at Object.g [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:51669)
    at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:55750)
    at n.Class.derive._oncancel._run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:57071)
    at n.Class.derive._oncancel._error (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:56588)
    at e.resolveErr (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1015423)
    at f (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1013710)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by mmauri** [comment]
BTW after restarting vscode, I managed to compile the project.

**Comment by mmauri** [comment]
Compiling, but still getting the dependencies error ;(

**Comment by Gama11** [comment]
To clarify, the dependency view also doesn't work / doesn't show anything?

What does `haxelib config` return, and what's the path to your Lime / OpenFL installations?

**Comment by mmauri** [comment]
Haxe dependencies is empty
haxelib config-> in: D:\HaxeToolkit\haxe\lib\
lime & openfl installed thru haxelib, so they are in D:\HaxeToolkit\haxe\lib

Maybe it is not working because they aren't in c: ??

hope this helps

**Comment by Gama11** [comment]
Hm... that's all pretty standard, the drive being different shouldn't matter...

**Comment by Gama11** [comment]
What's the content of your `bin/html5/debug/haxe/debug.hxml` file?

**Comment by mmauri** [comment]
-main ApplicationMain 
--macro openfl._internal.utils.ExtraParams.include()
-cp D:/HaxeToolkit/haxe/lib/openfl/5,1,5
-D openfl=5.1.5
--macro lime.Lib.extraParams()
-cp D:/HaxeToolkit/haxe/lib/lime/5,2,1
-D lime=5.2.1
-cp D:/HaxeToolkit/haxe/lib/actuate/1,8,7
-D actuate=1.8.7
-lib hscript
-cp D:/HaxeToolkit/haxe/lib/haxeui-core-DEV
-D haxeui-core=0.0.0
-cp D:/HaxeToolkit/haxe/lib/haxeui-openfl/git
-D haxeui-openfl=0.0.0
-cp src
-D tools=5.2.1
-D howlerjs
-D no-compilation
-D lime-opengl
-D openfl-html5
-D lime-html5
-D fdb
-D html5
-D web
--remap flash:openfl
-js bin/html5/debug/bin/KaizenHaxeWebV2.js
-cp bin/html5/debug/haxe
-D html5
-debug

**Comment by Gama11** [comment]
Oh, that explains a lot. :) What's the deal with the `D:/HaxeToolkit/haxe/lib/haxeui-core-DEV` classpath - did you manually create that, and what's inside?

The expected structure is `<haxelib-repo>/<lib-name>/<version>`, which is the case for both libs installed from `haxelib git` and `haxelib install`.

**Comment by mmauri** [comment]
Aha!!
It is an snapshot of the gh repo. I am going to fix it. Sorry for wasting your time.

BTW: vsHaxe is a huge improvement for haxe-> Js development!
I have managed to set breakpoints & debug inside vscode, without going while generating js.
Using Chrome Debugger extension, a local web server & source maps, quick & easy. 

Huge time saver, and finally we can say goodbye to always use trace() & js.lib.debug
Congrats!!!

**Comment by Gama11** [comment]
Not a waste of time, this still shouldn't break it. :)

So, is the repo actually properly installed in haxelib / listed when you run haxelib list? You just manually put it there?

**Comment by mmauri** [comment]
It was my mistake I moved manually there.
This is my haxelib list output:

C:\Users\MarcMauri>haxelib list
actuate: [1.8.7]
as3hx: git [dev:d:\HaxeToolkit\haxe\lib\as3hx/git]
box2d: [1.2.3]
dox: [1.1.0]
format: 3.2.1 [3.3.0]
haxeui-core: git [dev:D:\HaxeToolkit\haxe\lib\haxeui-core-DEV]
haxeui-openfl: git [dev:d:\HaxeToolkit\haxe\lib\haxeui-openfl/git]
hscript: [2.0.7]
hxargs: [3.0.2]
hxcpp: [3.4.64]
hxleaflet: [git]
hxparse: [4.0.0]
lime-samples: [4.0.1]
lime: 5.0.0 5.0.2 5.0.3 5.1.0 [5.2.1]
modestmaps-haxe: [3.3.6] img LICENSE.md README.md samples
modestmaps-openfl: git [dev:d:\HaxeToolkit\haxe\lib\modestmaps-openfl/git]
openfl-samples: 4.9.0 5.1.0 [5.1.1]
openfl: 5.1.0 5.1.1 5.1.2 5.1.3 [5.1.5]
perf.js: [1.1.8]
pixijs: [4.5.1]
react: 1.2.0 [1.2.1]
starling: [1.8.10]
swf: [2.3.1]

**Comment by Gama11** [comment]
Ah, so you installed it via `haxelib dev`. Thanks, I know how to handle it now. :)

**Comment by mmauri** [comment]
There are libs installed with dev like modestmaps-openfl
,and haxeui-core-DEV which is manually moved to the directory and set as dev, but it shouldn't be here.

Let me try to move it outside, so we can confirm this is the case.
