### ISSUE TITLE
Persistent CPU usage

### ISSUE THREAD

**Issue by kevinresol** [vshaxe/vshaxe#149]
I found that sometimes it is stuck at "initializing completion cache" and results in a continuous CPU usage. I observed that it happens when the codebase has compilation error while the vscode window is opened. (i.e. this can be reproduced on my project by: writing some invalid code, then run "reload window") Manually triggering a "restart haxe language server" will fix it though.

But I can't reproduce it in a minimal project ...

**Comment by Gama11** [comment]
"initializing completion cache" getting stuck sometimes is a known issue, but that's normally only a visual / cosmetic issue, i.e. should not result in increased CPU usage or anything like that...

**Comment by nadako** [comment]
> should not result in increased CPU usage

Not sure about that. Could be something related to `MessageReader` indefinitely trying to read and parse data from the haxe socket if it's given invalid (huge) length number.

**Comment by kevinresol** [comment]
"Stuck" just started:
![image](https://user-images.githubusercontent.com/1103788/27952674-b58b76e8-633b-11e7-8ee8-ecac9719d4a8.png)

Stuck for some time, then run "restart haxe language server":
![image](https://user-images.githubusercontent.com/1103788/27952692-c261e8de-633b-11e7-973e-b8bcb4024ffd.png)

**Comment by Gama11** [comment]
Ok, that seems pretty bad.. @nadako do you think this could be detected on the vshaxe side? I.e. "if message length is > n, Haxe probably sent us an invalid message".

This might already be fixed on Haxe dev, but that's not gonna help us for a while / until a new Haxe version is released.

**Comment by nadako** [comment]
gotta find out the actual cause. it should only process chunks of data on actual "data received" event, so it might be something different...

**Comment by kevinresol** [comment]
Another relevant information is that I'm using haxeshim. But judging from the fact that the CPU usage does not come from the haxe process itself, I guess it is not from haxeshim. 

I'll try to reproduce it though

**Comment by kevinresol** [comment]
Can you try a minimal project with `-lib dummy` so haxe fails with not-found library? Seems triggering the bug for me.

**Comment by Gama11** [comment]
That doesn't trigger the error for me.

**Comment by Gama11** [comment]
Definitely seems like a haxeshim bug, after installing it, "initializing completion" gets stuck with `-lib dummy`. I also get this:

![](http://i.imgur.com/8u7EoBp.png)

**Comment by Gama11** [comment]
Yep, it sends the error to stderr when it should go to stdout (don't ask, Haxe's approach there is ... interesting):

![](http://i.imgur.com/HXPgVDt.png)

Notice the insane message length. When running in `-D display-stdin` mode, Haxe is expected to prefix messages with the message length for all communication (and output errors to stdout in order not to break this, though that doesn't always work: https://github.com/HaxeFoundation/haxe/issues/6363)

**Comment by kevinresol** [comment]
Probably need to ping @back2dos

**Comment by Gama11** [comment]
I wonder if this is related to #58 - that also causes some crazy CPU usage.

**Comment by Gama11** [comment]
I assume this is no longer an issue since there hasn't been any activity here for a year? Let me know if that's not the case, but either way this seemed to be more of a problem with haxeshim than vshaxe.

**Comment by frabbit** [comment]
@Gama11 this is still an issue for me, am i the only one?

**Comment by kevinresol** [comment]
This is still an issue for me. CPU get stuck at 100% for the process "Code Helper". Killing it at OS-level will cause vshaxe to error:

```
[Info  - 2:25:04 PM] Connection to server got closed. Server will restart.
[Error - 2:25:04 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
    at Object.dispose (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:14862)
    at Object.dispose (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:62302)
    at t.LanguageClient.handleConnectionClosed (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:62477)
    at t.LanguageClient.handleConnectionClosed (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:150940)
    at t (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:60626)
    at invoke (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:68983)
    at r.fire (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:69713)
    at V (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:6797)
    at invoke (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:68983)
    at r.fire (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:69713)
    at d.fireClose (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:71900)
    at Socket.readable.on (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:72657)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close (net.js:606:12)
[Error - 2:25:04 PM] Request textDocument/foldingRange failed.
Error: Connection got disposed.
    at Object.dispose (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:14862)
    at Object.dispose (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:62302)
    at t.LanguageClient.handleConnectionClosed (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:62477)
    at t.LanguageClient.handleConnectionClosed (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:150940)
    at t (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:60626)
    at invoke (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:68983)
    at r.fire (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:69713)
    at V (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:6797)
    at invoke (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:68983)
    at r.fire (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:69713)
    at d.fireClose (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:71900)
    at Socket.readable.on (/Users/kevin/.vscode/extensions/nadako.vshaxe-2.16.4/bin/client.js:1:72657)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close (net.js:606:12)
```

After a few seconds the "Code Helper" process will come back and the problem will occur again.
