### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by sh-dave** [vshaxe/vshaxe#249]
This happens in projects where i use [lix](https://github.com/lix-pm/lix.client) to manage dependencies, and also in all my Kha based project. I've read #141 but this seems to be slightly different.

Attached is a small project showcasing the problem with lix, and also the console log i get in vscode's developer tools panel.

[vshaxe-split-issue.zip](https://github.com/vshaxe/vshaxe/files/2122552/vshaxe-split-issue.zip)

```shell
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2265 Error: Cannot read property 'split' of undefined
	at Function.haxe_io_Path.normalize (C:\Users\dklein\.vscode\extensions\nadako.vshaxe-2.0.1\bin\client.js:545:13)
	at Function.vshaxe_view_dependencies_DependencyResolver.get_haxelibRepo (C:\Users\dklein\.vscode\extensions\nadako.vshaxe-2.0.1\bin\client.js:2036:75)
	at vshaxe_view_dependencies_DependencyResolver.getDependencyInfo (C:\Users\dklein\.vscode\extensions\nadako.vshaxe-2.0.1\bin\client.js:2087:65)
	at Array.map (native)
	at Function.vshaxe_view_dependencies_DependencyResolver.resolveDependencies (C:\Users\dklein\.vscode\extensions\nadako.vshaxe-2.0.1\bin\client.js:2025:20)
	at vshaxe_view_dependencies_DependencyTreeView.refreshDependencies (C:\Users\dklein\.vscode\extensions\nadako.vshaxe-2.0.1\bin\client.js:2233:71)
	at vshaxe_view_dependencies_DependencyTreeView.getChildren (C:\Users\dklein\.vscode\extensions\nadako.vshaxe-2.0.1\bin\client.js:2307:32)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:485:478
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:887
	at new n.Class.derive._oncancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:83:776)
	at Object.t.asWinJsPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:850)
	at t.fetchChildrenNodes (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:485:430)
	at t.getChildren (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:483:292)
	at e.$getChildren (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:481:487)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:832)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:550)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:631)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:400)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:634:315
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:395
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:95:432
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:338)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
﻿```

**Comment by Gama11** [comment]
Hm, I don't particularly want to install Lix to test this since it's rather invasive and hard to get rid of again... (https://github.com/lix-pm/haxeshim/issues/23)

@back2dos On Windows, vshaxe assumes that there's a folder named `std` next to the Haxe executable, is that not the case with lix / haxeshim?

**Comment by Gama11** [comment]
Or maybe the more likely issue is that `where haxe` is failing. But there's already a null check there...

**Comment by sh-dave** [comment]
It's setup locally for the project, so it shouldn't do anything else than what npm already does? And to kill the downloads, you can just delete

- windows: `/Users/USERNAME/AppData/Roaming/haxe`
- linux: `~/haxe`
- dunno about osx

**Comment by back2dos** [comment]
@Gama11 you don't have to install lix globally. In fact, if you take the zip given by David and run `npm install` it'll install lix locally and point vscode to it.

> On Windows, vshaxe assumes that there's a folder named std next to the Haxe executable, is that not the case with lix / haxeshim?

Indeed, this is not the case. The executable (the shim) is where npm puts it, the stdlib is where lix puts it (next to the actual haxe executable).

I wish we could remove all of these hard coded conventions and let the haxe compiler expose this kind of stuff. To elaborate, with haxeshim you can:

- `haxe --run show-version`: this gives you the version and the stdlib path
- `haxe --run resolve-args arg1 arg2 arg3`: this resolves all arguments, like `-lib` and `hxml`

I can make a PR for the dependency explorer to use haxeshim if it's detected. It'll take an extra system call though.

**Comment by Gama11** [comment]
Interesting, I didn't know local installs like that were possible.

Hm... I'm not sure lix is popular enough at this point to warrant hardcoding support for it in vshaxe. And anyway, it might make sense to wait and see if anything happens depdency manager / haxelib-wise in Haxe 4...

**Comment by back2dos** [comment]
> I'm not sure lix is popular enough at this point to warrant hardcoding support for it in vshaxe

That's a bit of a chicken and egg thing though. As a Haxe developer I'm sure you're familiar with the situation ;)

**Comment by sh-dave** [comment]
Hm, how does setting `HAXE_STD_PATH` help with this issue; the actual error seems to be the `null` value passed when an empty array is returned?https://github.com/vshaxe/vshaxe/blob/0650e0c1b72cf56ee529e08f27f0371e4fc8b08b/src/vshaxe/view/dependencies/DependencyResolver.hx#L44

**Comment by Gama11** [comment]
You're right, looks like I interpreted the stacktrace incorrectly (I thought the error was within `getStandardLibraryPath()` because I used the wrong line number...). Not sure why `haxelib config` wouldn't work with Lix though?

**Comment by sh-dave** [comment]
I guess b/c it's installed locally, so there is no actual haxelib program / shim to call. To run something like that from commandline i usually use `npx` so say `npx haxelib config` or `npx haxe --version`. A fix might be to provide another settings.js value like `haxe.executable` for haxlib.

```json
"haxe.haxelib.executable": {
    "windows": "node_modules/.bin/haxelib.cmd",
    "linux": "node_modules/.bin/haxelib"
}
```

or maybe even simply not passing the path to `haxe.io.Path.normalize` in case it's null.

**Comment by Gama11** [comment]
We should do both - fix the crash, and implement a haxelib executable setting (see #227, but I see you already commented there).

**Comment by sh-dave** [comment]
Oh yeah, i forgot about that it might be related, and thinking a bit harder i also remembered this one that might be resolved then as well: https://github.com/lix-pm/lix.client/issues/27
