### ISSUE TITLE
Latest update (2.9.1) won't load anymore

### ISSUE THREAD

**Issue by deepnight** [vshaxe/vshaxe#339]
It doesn't seem to be able to detect any HXML task anymore. Version 2.9.0 works fine.

I get this if I try to build:
![image](https://user-images.githubusercontent.com/1671695/56567401-1bb76300-65b5-11e9-8df9-1c7da725937e.png)

It actually cannot auto-detect tasks:

```
Error: The hxml task detection didn't contribute a task for the following configuration:
{
    "label": "HL debug",
    "type": "hxml",
    "file": "hl.debug.hxml",
    "presentation": {
        "reveal": "never",
        "panel": "dedicated",
        "clear": true
    },
    "problemMatcher": [
        "$haxe"
    ],
    "group": {
        "kind": "build",
        "isDefault": true
    }
}
The task will be ignored.
```

Same goes for all existing tasks from my tasks.json. If i try to restart haxe server:
![image](https://user-images.githubusercontent.com/1671695/56567493-591bf080-65b5-11e9-9c52-07da3cfad679.png)
I get: 

![image](https://user-images.githubusercontent.com/1671695/56567511-646f1c00-65b5-11e9-95a8-9bcce4e7c63b.png)

Here is my **tasks.json**:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "HL debug",
            "type": "hxml",
            "file": "hl.debug.hxml",
            "presentation": {
                "reveal": "never",
                "panel": "dedicated",
                "clear": true
            },
            "problemMatcher": ["$haxe"],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },

        {
            "label": "HL release",
            "type": "hxml",
            "file": "hl.hxml",
            "presentation": {
                "reveal": "never",
                "panel": "dedicated",
                "clear": true
            },
            "problemMatcher": ["$haxe"],
        },

        {
            "label": "JS release",
            "type": "hxml",
            "file": "js.hxml",
            "presentation": {
                "reveal": "never",
                "panel": "dedicated",
                "clear": true
            },
            "problemMatcher": ["$haxe"],
        },

        {
            "label": "SWF release",
            "type": "hxml",
            "file": "flash.hxml",
            "presentation": {
                "reveal": "never",
                "panel": "dedicated",
                "clear": true
            },
            "problemMatcher": ["$haxe"],
        }
    ]
}
```

**Comment by Gama11** [comment]
Hm, seems to work ok here.. Is there anything in the dev console about vshaxe failing to activate?

**Comment by deepnight** [comment]
This is the content of my Log (Extension Host) window:
![image](https://user-images.githubusercontent.com/1671695/56573485-72c33500-65c1-11e9-88d6-25337ed196a1.png)

Log (shared)
![image](https://user-images.githubusercontent.com/1671695/56573453-60e19200-65c1-11e9-941a-0039bf46d218.png)

There's no Haxe log window.

**Comment by Gama11** [comment]
What about the dev console?  Help, Toggle Developer Tools

VSCode version?

**Comment by deepnight** [comment]
Thanks, I didn't know about this one. It seems the culprit is actually the extension **vscode-icons**. But for some reason, the issue only happens when **vshaxe** is set to 2.9.1 (and not 2.9.0 or less).

```
[Extension Host] debugger listening on port 23270
extensionService.ts:800 Activating extension 'vscode-icons-team.vscode-icons' failed: Cannot find module './contributions'.
_logMessageInConsole @ extensionService.ts:800
_logOrShowMessage @ extensionService.ts:814
(anonymous) @ mainThreadExtensionService.ts:65
(anonymous) @ errors.ts:184
n @ errors.ts:184
$onExtensionActivationError @ mainThreadExtensionService.ts:63
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
console.ts:134 [Extension Host] Activating extension `vscode-icons-team.vscode-icons` failed:  Cannot find module './contributions'
t.log @ console.ts:134
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
console.ts:134 [Extension Host] Here is the error stack:  Error: Cannot find module './contributions'
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
	at Function.Module._load (internal/modules/cjs/loader.js:528:25)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:729:537)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:639)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:655:197)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (D:\Dropbox\MT\vscode\.vscode\extensions\vscode-icons-team.vscode-icons-8.6.0\out\src\models\index.js:6:10)
	at Object.<anonymous> (D:\Dropbox\MT\vscode\.vscode\extensions\vscode-icons-team.vscode-icons-8.6.0\out\src\models\index.js:15:3)
	at Module.t._initNodeRequire.r._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:729:537)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:639)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:655:197)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (D:\Dropbox\MT\vscode\.vscode\extensions\vscode-icons-team.vscode-icons-8.6.0\out\src\index.js:4:18)
	at Object.<anonymous> (D:\Dropbox\MT\vscode\.vscode\extensions\vscode-icons-team.vscode-icons-8.6.0\out\src\index.js:20:3)
	at Module.t._initNodeRequire.r._compile (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:729:537)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:639)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:655:197)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.i [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:31:542)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:717:918
	at E._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:718:2)
	at E._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:716:772)
	at E.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:714:224)
	at Generator.next (<anonymous>)
	at n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:11:176)
	at new Promise (<anonymous>)
	at n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:10:975)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:713:946)
	at p._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:457:765)
	at define._activateExtensions.i.length.Promise.all.o.map.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:457:449)
	at Array.map (<anonymous>)
	at p._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:457:437)
	at p.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:455:375)
	at E._activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:715:434)
	at E._handleEagerExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:719:365)
	at define._startExtensionHost._readyToRunExtensions.wait.then (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:722:430)
console.ts:134 [Extension Host] (node:3572) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:134
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
```

**Comment by deepnight** [comment]
That's weird, it now works fine after disabling/enabling vscode-icons. 🤔

**Comment by Gama11** [comment]
Wtf... FWIW, I'm using vscode-icons too.

**Comment by Gama11** [comment]
>But for some reason, the issue only happens when vshaxe is set to 2.9.1 (and not 2.9.0 or less).

That makes no sense to me, 2.9.1 only has two minor changes compared to 2.9.1...

**Comment by Gama11** [comment]
@ncannasse reported that he got the following in the output channel:

>The language client requires VS Code version ^1.33.0 but received version 1.32.3

And I can also reproduce that with VSCode 1.32. Any chance that's related to this?

**Comment by Gama11** [comment]
Since nobody else seems to be running into this, and there isn't any easy way to reproduce, I will close here. However, let me know if you run into this again or have good repro steps.
