### ISSUE TITLE
Haxe's language server starts with wrong --cwd argument

### ISSUE THREAD

**Issue by mikicho** [vshaxe/vshaxe#348]
I *think* this is vshaxe issue (and not vscode one..).

### environment:
- I'm using lix
- Working with Remote - WSL extension

Version: 1.35.0-insider (user setup)
Commit: 6b081a9f0089062b2cd105e1f1ab366591291534
Date: 2019-05-24T21:28:41.464Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

### problem
My workspace has the following folder structure:
```
root
  - client
    - client.hxml
    - .haxerc
  - server
    - server.hxml
    - .haxerc
```

`.vscode/settings.json` contains:
```
{
    "haxe.configurations": [ ["--cwd", "src/client", "client.hxml"], ["--cwd", "src/server", "server.hxml"] ],
}
```

For some reason, Haxe's language server starts with a wrong path only *if* the path is correct ><
i.e, for the above configuration, for server.hxml, the hxml path is:
```
Haxe language server started
Listening on port 6000
Building Cache...
Haxe server restart requested: Haxe process was killed
Done.
Building Cache...
Restarted Haxe server: Haxe process was killed
Haxe server restart requested: Haxe process was killed
Done.
Building Cache...
Restarted Haxe server: Haxe process was killed

Error message from the compiler:

s:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '{workspace_root}/src/server/src/server/server.hxml'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at haxeshim_Resolver.processHxml ({user_folder}/AppData/Roaming/npm/node_modules/lix/bin/haxeshim.js:7765:56)
    at haxeshim_Resolver.process ({user_folder}/AppData/Roaming/npm/node_modules/lix/bin/haxeshim.js:7858:11)
    at haxeshim_Resolver.resolve ({user_folder}/AppData/Roaming/npm/node_modules/lix/bin/haxeshim.js:7676:8)
    at haxeshim_Scope.resolve ({user_folder}/AppData/Roaming/npm/node_modules/lix/bin/haxeshim.js:7542:24)
    at processData 
({user_folder}/AppData/Roaming/npm/node_modules/lix/bin/haxeshim.js:6589:88)
    at reduce ({user_folder}/AppData/Roaming/npm/node_modules/lix/bin/haxeshim.js:6607:7)
    at Socket.<anonymous> ({user_folder}/AppData/Roaming/npm/node_modules/lix/bin/haxeshim.js:6634:4)
    at Socket.emit (events.js:189:13)
```
(`src/server` occur twice)

BUT if the path is wrong, ie:
```
{
    "haxe.configurations": [ ["--cwd", "src/client", "client.hxml"], ["--cwd", "src/server11111", "server.hxml"] ],
}
```
I get:
```
...
Error: ENOENT: no such file or directory, open {workspace_root}/src/server11111/server.hxml'
...
```
(the path is correct now, but not exist in my file system..)

I tried to change folders/files names.

**Comment by mikicho** [comment]
I don't have a proper dev environment for vshaxe but I'm trying to find the problem.
I think the problem caused by the `HxmlDiscovery`:
https://github.com/vshaxe/vshaxe/blob/e77d49323612ba5ce636cad8732c8d2cb4bfc310/src/vshaxe/tasks/HxmlTaskProvider.hx#L20

**Comment by Gama11** [comment]
I expect this only produces with WSL / VSCode remote?

Might be good to isolate aways lix at least to make sure that's not causing any issues.

**Comment by mikicho** [comment]
@Gama11 
How I can temporary disable lix?

I succeeded to reproduce the problem with a new project in a stable version of vscode, without WSL and Haxe 3.4.7
Haxe language server started
Listening on port 6001
Haxe version does not support JSON-RPC, using legacy --display API.
Building Cache...
Haxe server restart requested: Haxe process was killed
Haxe version does not support JSON-RPC, using legacy --display API.
Building Cache...
Restarted Haxe server: Haxe process was killed
Haxe server restart requested: Haxe process was killed
Haxe version does not support JSON-RPC, using legacy --display API.
Building Cache...
Restarted Haxe server: Haxe process was killed

Error message from the compiler:

s:115
    throw err;
    ^

Error: ENOENT: no such file or directory, open '{workspace_root}/src/server/src/server/server.hxml'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at haxeshim_Resolver.processHxml ({user_folder}\AppData\Roaming\npm\node_modules\lix\bin\haxeshim.js:7765:56)
    at haxeshim_Resolver.process ({user_folder}\AppData\Roaming\npm\node_modules\lix\bin\haxeshim.js:7858:11)
    at haxeshim_Resolver.resolve ({user_folder}\AppData\Roaming\npm\node_modules\lix\bin\haxeshim.js:7676:8)
    at haxeshim_Scope.resolve ({user_folder}\AppData\Roaming\npm\node_modules\lix\bin\haxeshim.js:7542:24)
    at processData ({user_folder}\AppData\Roaming\npm\node_modules\lix\bin\haxeshim.js:6589:88)
    at reduce ({user_folder}\AppData\Roaming\npm\node_modules\lix\bin\haxeshim.js:6607:7)
    at Socket.<anonymous> ({user_folder}\AppData\Roaming\npm\node_modules\lix\bin\haxeshim.js:6634:4)
    at Socket.emit (events.js:182:13)

**Comment by mikicho** [comment]
It seems like lix problem.
