### ISSUE TITLE
Completion doesn't work

### ISSUE THREAD

**Issue by pojkabruh** [vshaxe/vshaxe#354]
Hello!
I am trying to try out the HaxeFlixel. I have installed all the required libraries. 
The problem is: the Auto-completion does not work.
It works only for a short duration of time after creating a new project and then a few times after restarting the computer. It is a bit random.

Output when I open the VS Code for the first time after restarting the computer:

Haxe language server started
Listening on port 6000
Listening on port 6000
[Error - 1:07:39 PM] Request textDocument/codeLens failed.
  Message: Unhandled method textDocument/codeLens
  Code: -32601 
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:6000
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1492:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:55:10)
Emitted 'error' event at:
    at emitErrorNT (net.js:1357:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Info  - 1:07:40 PM] Connection to server got closed. Server will restart.
Listening on port 6000
[Error - 1:07:40 PM] Request textDocument/codeLens failed.
  Message: Unhandled method textDocument/codeLens
  Code: -32601 
Haxe version does not support JSON-RPC, using legacy --display API.
Building Cache...
/////////////////////////////////////////////////////////////////////////////////////////////

And so it goes on forever...
After restarting the VS Code:

Haxe language server started
Listening on port 6000
[Error - 1:11:59 PM] Request textDocument/codeLens failed.
  Message: Unhandled method textDocument/codeLens
  Code: -32601 
Haxe version does not support JSON-RPC, using legacy --display API.
Building Cache...
Done.

//As soon as I try to do anything with the code

[Error - 1:13:39 PM] Request textDocument/hover failed.
  Message: Error: No completion point was found
  Code: -32603 
[Error - 1:13:51 PM] Request textDocument/completion failed.
  Message: Error: No completion point was found
  Code: -32603 
/////////////////////////////////////////////////////////////////////////////////////////////

So. What does this "No completion point was found" mean and what should I try doing to fix it?

**Comment by pojkabruh** [comment]
It's not really an issue with the vshaxe is it
