### ISSUE TITLE
vsix file is missing hlcode.json

### ISSUE THREAD

**Issue by sebthom** [vshaxe/vshaxe#490]
hlcode.json is referenced under `grammars` in [package.json](https://github.com/vshaxe/vshaxe/blob/37086af33c9737c801669cbf7fc575081386fd10/package.json#L958) but is missing in the archive available at the marketplace.

![image](https://user-images.githubusercontent.com/426959/116737593-b2fbf000-a9f1-11eb-8fa3-bd287a6302cc.png)

This for example results in the following error when loaded into [Eclipse Theia](https://theia-ide.org) resulting in Haxe syntax highlighting not working at all.
```
Error: Cannot find module 'D:\theia\resources\app\plugins\nadako.vshaxe\extension\syntaxes\hlcode.json'
Require stack:
- D:\theia\resources\app\node_modules\@theia\plugin-ext\lib\hosted\node\scanners\grammars-reader.js
- D:\theia\resources\app\node_modules\@theia\plugin-ext\lib\hosted\node\scanners\scanner-theia.js
- D:\theia\resources\app\node_modules\@theia\plugin-ext\lib\hosted\node\plugin-ext-hosted-backend-module.js
- D:\theia\resources\app\node_modules\@theia\plugin-ext\lib\hosted\node-electron\plugin-ext-hosted-electron-backend-module.js
- D:\theia\resources\app\node_modules\@theia\plugin-ext\lib\plugin-ext-backend-electron-module.js
- D:\theia\resources\app\src-gen\backend\server.js
- D:\theia\resources\app\src-gen\backend\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at GrammarsReader.readGrammar (D:\theia\resources\app\node_modules\@theia\plugin-ext\lib\hosted\node\scanners\grammars-reader.js:67:23)
    at GrammarsReader.readGrammars (D:\theia\resources\app\node_modules\@theia\plugin-ext\lib\hosted\node\scanners\grammars-reader.js:48:36)
    at VsCodePluginScanner.TheiaPluginScanner.getContribution (D:\theia\resources\app\node_modules\@theia\plugin-ext\lib\hosted\node\scanners\scanner-theia.js:186:52)
    at HostedPluginReader.readContribution (D:\theia\resources\app\node_modules\@theia\plugin-ext\lib\hosted\node\plugin-reader.js:188:24)
    at HostedPluginDeployerHandler.<anonymous> (D:\theia\resources\app\node_modules\@theia\plugin-ext\lib\hosted\node\hosted-plugin-deployer-handler.js:292:60)
root INFO Deploying backend plugin "vshaxe@2.23.1" from "D:\theia\resources\app\plugins\nadako.vshaxe\extension\bin\index.js"
```

**Comment by sebthom** [comment]
@Gama11 thanks for the quick fix!
