### ISSUE TITLE
Exception on workspace/didChangeWatchedFiles notification which references missing file .haxelsp/recording/current/repro.log

### ISSUE THREAD

**Issue by joshtynjala** [vshaxe/vshaxe#636]
Occasionally, vshaxe stops providing code intelligence in my projects after being open a couple of hours, even with completely valid code, and I need to restart the language server. _I don't have repo steps for that yet._

However, the last couple of times that it has happened, I've noticed the following exception in the Haxe Output log. Perhaps there's a missing check to determine if the file exists before opening it? Or maybe the directories need to be created first.

In case it is relevant, I don't actually have `haxe.serverRecording` enabled.

```
[Warn  - 10:39:28 AM] Exception while processing notification workspace/didChangeWatchedFiles: Error: ENOENT: no such file or directory, open '.haxelsp/recording/current/repro.log'

Called from Object.openSync (node:fs line 575 column 18)
Called from module at Object.func [as openSync] (node:electron/js2c/node_init:2:2214)
Called from module at /Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.0/server/bin/server.js:1:527169
Called from Hr.print (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.0/server/bin/server.js line 1 column 527548)
Called from Hr.appendLines (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.0/server/bin/server.js line 1 column 527133)
Called from Hr.onFileEvent (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.0/server/bin/server.js line 1 column 523983)
Called from gt.onDidChangeWatchedFiles (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.0/server/bin/server.js line 1 column 288169)
Called from Ri.handleNotification (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.0/server/bin/server.js line 1 column 576392)
Called from Ri.handleMessage (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.0/server/bin/server.js line 1 column 575213)
Called from Mi.onData (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.0/server/bin/server.js line 1 column 578421)
```

**Comment by AlexHaxe** [comment]
@kLabz sorry, didn't see your self assign, I assume my fix addresses the issue. let me know if it needs additional fixes

**Comment by kLabz** [comment]
No problem, thanks for fixing this :)

**Comment by AlexHaxe** [comment]
@joshtynjala vshaxe 2.32.1 should be out now. let us know if you still experience this issue.

**Comment by joshtynjala** [comment]
Thanks! I have not seen the original exception from the workspace/didChangeWatchedFiles notification since updating to vshaxe 2.32.1.

However, I'm still seeing vshaxe code intelligence stop working after leaving VSCode running for several hours. There are a few different exceptions that I see in the vshaxe output log.

## Exception on textDocument/hover request: Cannot read properties of undefined (reading 'start')

On today's crash, this is the first exception that I see in the log. It repeats many times.

```
[Error - 8:50:33 AM] Request textDocument/hover failed.
  Message: Cannot read properties of undefined (reading 'start')
  Code: -32603 
Cannot read properties of undefined (reading 'start')

Called from module TypeError: Cannot read properties of undefined (reading 'start')
Called from er.byteRangeToCharacterRange (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 469683)
Called from module at /Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js:1:324549
Called from ji.resolve (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 289970)
Called from Ri.handleResponse (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 576953)
Called from Ri.handleMessage (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 575122)
Called from module at /Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js:1:280904
Called from Ir.processResult (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 502478)
Called from Ir.onData (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 501983)
Called from jr.onMessage (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 517350)
Called from Rr.onData (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 503780)
```

## Exception on textDocument/hover request: Uncaught exception too many open files

Next, I see exactly one of this exception in the log.

```
[Error - 12:29:49 PM] Request textDocument/hover failed.
  Message: Uncaught exception too many open files
  Code: -32603 
```

## Exception on textDocument/hover request: Unexpected end of JSON input

After the previous exception, this one repeats until the end.

```
[Error - 12:29:49 PM] Request textDocument/hover failed.
  Message: Exception while handling Haxe completion response: Unexpected end of JSON input

Called from <unknown>.accessSync (node:fs line 246 column 11)
Called from t.accessSync (node:electron/js2c/node_init line 2 column 9017)
Called from <unknown>.exists (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 646749)
Called from <unknown>.determineConfig (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 97103)
Called from <unknown>.loadConfig (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 96086)
Called from <unknown>.formatText (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 473378)
Called from <unknown>.organizeImportGroup (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 366648)
Called from <unknown>.organizeImportGroups (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 366268)
Called from <unknown>.organizeImports (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 365423)
Called from <unknown>.createOrganizeImportActions (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 390751)
  Code: -32603 
```

**Comment by AlexHaxe** [comment]
I believe they all have different causes, so would you mind opening individual issues for them?

e.g. in the last one it looks like there's a broken `hxformat.json` somewhere in your folder hierarchy
