### ISSUE TITLE
Exception on textDocument/hover request: Cannot read properties of undefined (reading 'start')

### ISSUE THREAD

**Issue by joshtynjala** [vshaxe/vshaxe#641]
After code intelligence stopped working, I see the following exception (among others) in the vshaxe output log. 

```
[Error - 8:50:33 AM] Request textDocument/hover failed.
  Message: Cannot read properties of undefined (reading 'start')
  Code: -32603 
Cannot read properties of undefined (reading 'start')

Called from module TypeError: Cannot read properties of undefined (reading 'start')
Called from er.byteRangeToCharacterRange (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 469683)
Called from module at /Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js:1:324549
Called from ji.resolve (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 289970)
Called from Ri.handleResponse (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 576953)
Called from Ri.handleMessage (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 575122)
Called from module at /Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js:1:280904
Called from Ir.processResult (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 502478)
Called from Ir.onData (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 501983)
Called from jr.onMessage (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 517350)
Called from Rr.onData (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 503780)
```

**Comment by joshtynjala** [comment]
Followup: I restarted the language server to continue working. In the output log, I see that this one has happened a couple of times since the restart. However, code intelligence is still working correctly in my editor. So perhaps something that can happen when the code temporarily contains invalid syntax or has some other compiler error.

**Comment by AlexHaxe** [comment]
seems like the hover request didn't return a proper `Range` object (with `start` field being null or non-existant).

I think a server recording would help identify the issue, which either requires a fix in Haxe and/or better checks on vshaxe side.

**Comment by joshtynjala** [comment]
According to the language server protocol specification, the `range` field on the `Hover` interface is optional.

**Comment by AlexHaxe** [comment]
not when talking to Haxe: https://api.haxe.org/haxe/display/HoverResult.html

the whole hover result might be null, but vshaxe checks for that. if it's not null then there should be a valid `Range` with `start` and `end` positions.

**Comment by joshtynjala** [comment]
I figured out a way to reproduce this error. I have simplified it to as small a test case as I can.

build.hxml

```hxml
--interp
--main Main
```

Main.hx

```haxe
class Main {
	static function main() {
		abc.xyz;
	}
}
```

Hover the mouse over any of the whitespace at the beginning of the line containing `abc.xyz`, or hover over the `xyz` field, to trigger the error:

```
[Error - 10:01:26 AM] Request textDocument/hover failed.
  Message: Cannot read properties of undefined (reading 'start')
  Code: -32603 
Cannot read properties of undefined (reading 'start')

Called from module TypeError: Cannot read properties of undefined (reading 'start')
Called from er.byteRangeToCharacterRange (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 469683)
Called from module at /Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js:1:324549
Called from ji.resolve (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 289970)
Called from Ri.handleResponse (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 576953)
Called from Ri.handleMessage (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 575122)
Called from module at /Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js:1:280904
Called from Ir.processResult (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 502478)
Called from Ir.onData (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 501983)
Called from jr.onMessage (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 517350)
Called from Rr.onData (/Users/joshtynjala/.vscode/extensions/nadako.vshaxe-2.32.1/server/bin/server.js line 1 column 503780)
```

Note: If you replace `abc.xyz` with just `abc`, the `Cannot read properties of undefined (reading 'start')` error does not occur when hovering the mouse over any part of the file.

Additionally, if you hover the mouse over over abc, you can see this error in the log:

```
[Error - 9:57:10 AM] Request textDocument/hover failed.
  Message: Unknown identifier : abc
  Code: -32603 
```
